In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
y_train_reshaped = y_train.to_numpy().reshape(-1, 1)
y_test_reshaped = y_test.to_numpy().reshape(-1, 1)

scy=StandardScaler()
y_train=scy.fit_transform(y_train_reshaped)
y_test=scy.transform(y_test_reshaped)

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['sqrt','log2'],'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits


C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
20 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 378, in fit
    raise ValueError(
ValueError: Some value(s) of y are negative whi

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [9]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8686234590628045


In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.099746      0.008209         0.005245        0.006626   
1        0.821216      0.013969         0.031925        0.004834   
2        0.085638      0.007804         0.003128        0.006256   
3        0.809696      0.017735         0.031401        0.002482   
4        0.193990      0.010902         0.007266        0.007019   
5        1.876912      0.022836         0.030551        0.006564   
6        0.193787      0.010078         0.002762        0.005525   
7        2.212953      0.392623         0.034130        0.011959   
8        0.084415      0.003496         0.005540        0.004530   
9        0.968748      0.248141         0.043614        0.007418   
10       0.111719      0.033067         0.008075        0.007131   
11       1.410516      0.091594         0.037666        0.007536   
12       0.001742      0.001939         0.000000        0.000000   
13       0.006288      0.005871         0.000000        0.000000   
14       0.007741      0.002000         0.000000        0.000000   
15       0.003870      0.005822         0.000000        0.000000   

   param_criterion param_max_features param_n_estimators  \
0    squared_error               sqrt                 10   
1    squared_error               sqrt                100   
2    squared_error               log2                 10   
3    squared_error               log2                100   
4   absolute_error               sqrt                 10   
5   absolute_error               sqrt                100   
6   absolute_error               log2                 10   
7   absolute_error               log2                100   
8     friedman_mse               sqrt                 10   
9     friedman_mse               sqrt                100   
10    friedman_mse               log2                 10   
11    friedman_mse               log2                100   
12         poisson               sqrt                 10   
13         poisson               sqrt                100   
14         poisson               log2                 10   
15         poisson               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'squared_error', 'max_features':...           0.790536   
1   {'criterion': 'squared_error', 'max_features':...           0.801254   
2   {'criterion': 'squared_error', 'max_features':...           0.771810   
3   {'criterion': 'squared_error', 'max_features':...           0.810386   
4   {'criterion': 'absolute_error', 'max_features'...           0.778656   
5   {'criterion': 'absolute_error', 'max_features'...           0.798671   
6   {'criterion': 'absolute_error', 'max_features'...           0.793790   
7   {'criterion': 'absolute_error', 'max_features'...           0.803923   
8   {'criterion': 'friedman_mse', 'max_features': ...           0.790642   
9   {'criterion': 'friedman_mse', 'max_features': ...           0.805582   
10  {'criterion': 'friedman_mse', 'max_features': ...           0.768717   
11  {'criterion': 'friedman_mse', 'max_features': ...           0.806431   
12  {'criterion': 'poisson', 'max_features': 'sqrt...                NaN   
13  {'criterion': 'poisson', 'max_features': 'sqrt...                NaN   
14  {'criterion': 'poisson', 'max_features': 'log2...                NaN   
15  {'criterion': 'poisson', 'max_features': 'log2...                NaN   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.753517           0.819192           0.835199   
1            0.771371           0.835484           0.824003   
2            0.741715           0.816475           0.819180   
3            0.772837           0.832620           0.833743   
4            0.762724           0.816119           0.810845   
5            0.773223           0.836322           0.830460   
6            0.769433           0.810458           0.792459   
7            0.770206        

In [12]:
import pickle
filename="finalized_advancedtechniqueRFIandO).sav"

In [13]:
pickle.dump(grid,open(filename,'wb'))

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:25
BMI:45
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1


In [15]:
preinput=sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [16]:
preinput

array([[-1.03919296,  2.31963086,  0.75672907,  1.01127431,  2.00280702]])

In [17]:
loaded_model=pickle.load(open("finalized_advancedtechniqueRFIandO).sav", 'rb'))
result=loaded_model.predict(preinput)

In [18]:
result

array([2.29536295])

In [19]:
preoutput=scy.inverse_transform([result])


In [20]:
preoutput

array([[40258.0342622]])